In [1]:
from wikidataloader import WikidataQuery

# Linguists from Germany with birth places and gender

results = WikidataQuery.search(
    filters={"P31": "Q5", "P27": "Q183", "P106": "Q14467526"}, # {is_instance:human, country_of_origin:Germany, profession:linguist}
    select=[("P21", "Gender"), ("P19", "City of Birth")],
    limit=15,
    default_language="en"
).to_pandas()

results

                                   item Gender        City_of_Birth
0                        Hermann Weller   male     Schwäbisch Gmünd
1                             Hans Wehr   male              Leipzig
2                       Theodor Haecker   male            Mulfingen
3                   Gottfried Bernhardy   male  Gorzów Wielkopolski
4                    Wilhelm Streitberg   male   Rüdesheim am Rhein
5                 Adalbert Bezzenberger   male               Kassel
6                     Otto Gildemeister   male               Bremen
7                     Martin Haspelmath   male                 Hoya
8                          Werner Spies   male             Tübingen
9                        Wilhelm Schott   male                Mainz
10                        Theodor Bergk   male              Leipzig
11                   Johann Ernst Glück   male               Wettin
12  August Johann Gottfried Bielenstein   male              Jelgava
13            Rudolf Alexander Schröder   male               Bremen
14                       Gerhard Rohlfs   male               Berlin

In [2]:
# Images and temperatures of stars

results = WikidataQuery.search(
    filters={"P31": "Q523"}, # {is_instance:star}
    select=[("P6879", "Temperature"), ("P18", "image_url")],
    required_properties={"P18", "P6879"},
    limit=15,
    default_language="[AUTO_LANGUAGE]"
).to_pandas()

results

,item,Temperature,image_url
0,HD 164922,5393,http://commons.wikimedia.org/wiki/Special:File...
1,Beta Phoenicis,5090,http://commons.wikimedia.org/wiki/Special:File...
2,Kepler-78,5073,http://commons.wikimedia.org/wiki/Special:File...
3,NGC 4349-127,4512,http://commons.wikimedia.org/wiki/Special:File...
4,Paradys,4090,http://commons.wikimedia.org/wiki/Special:File...
5,RS Puppis,5068,http://commons.wikimedia.org/wiki/Special:File...
6,RS Puppis,5073,http://commons.wikimedia.org/wiki/Special:File...
7,Alpha Sagittae,5503,http://commons.wikimedia.org/wiki/Special:File...
8,KY Cygni,3500,http://commons.wikimedia.org/wiki/Special:File...
9,Pi Aurigae,3736,http://commons.wikimedia.org/wiki/Special:File...
10,HD 69830,5402,http://commons.wikimedia.org/wiki/Special:File...
11,Beta Aquarii,5465,http://commons.wikimedia.org/wiki/Special:File...
12,L 34-26,3406,http://commons.wikimedia.org/wiki/Special:File...
13,BD+20 2457,4259,http://commons.wikimedia.org/wiki/Special:File...
14,TZ Arietis,3154,http://commons.wikimedia.org/wiki/Special:File...

In [3]:
# Capital cities and languages of African countries with coordinates

results = WikidataQuery.search(
    filters={"P31": "Q3624078", "P30": "Q15"}, # {is_instance:country, continent:Africa}
    negative_filters={"P31": "Q3024240", "P31": "Q28171280"}, # not: {is_instance: historical_country, is_instance:ancient_civilization}
    select=[("P36", "Capital"), ("P37", "Language"), ("P625", "Coordinates")],
    limit=15,
    default_language="en"
).to_pandas()

results

,item,Capital,Language,Coordinates
0,Burundi,Gitega,English,Point(29.816667 -3.666667)
1,The Gambia,Banjul,English,Point(-15.5 13.5)
2,Mali,Bamako,Fula,Point(-4.0 17.0)
3,Democratic Republic of the Congo,Kinshasa,French,Point(23.656111111 -2.88)
4,Zimbabwe,Harare,Zimbabwe Sign Language,Point(30.0 -19.0)
5,Libya,Tripoli,Arabic,Point(17.0 27.0)
6,Cape Verde,Praia,Portuguese,Point(-23.7 15.3)
7,Angola,Luanda,Portuguese,Point(17.35 -12.35)
8,Malawi,Lilongwe,Tumbuka,Point(34.0 -13.0)
9,São Tomé and Príncipe,São Tomé,Portuguese,Point(6.6 0.316667)
10,Lesotho,Maseru,English,Point(28.25 -29.55)
11,Madagascar,Antananarivo,French,Point(47.0 -20.0)
12,Madagascar,Antananarivo,Malagasy,Point(47.0 -20.0)
13,Burundi,Gitega,French,Point(29.816667 -3.666667)
14,Comoros,Moroni,French,Point(43.7 -12.3)

In [4]:
# List of phrases

results = WikidataQuery.search(
    filters={"P31": "Q187931"}, # {is_instance:phrase}
    limit=15,
    default_language="en"
).to_pandas()

list(results["item"])

['To be, or not to be',
 'genius loci',
 'Item',
 'a picture is worth a thousand words',
 'Mulus',
 'Minus',
 'Cash is king',
 'That that is is that that is not is not is that it it is.',
 'Studia humanitatis',
 'Chorismos',
 'Concursus Dei',
 'Condictio causa data non secuta',
 'Condictio certae pecuniae',
 'Condictio certae rei',
 'Condictio ob causam finitam']