In [1]:
from wikidataloader import WikidataQuery

# Linguists from Germany with birth places and gender

results = WikidataQuery.search(
    filters={"P31": "Q5", "P27": "Q183", "P106": "Q14467526"}, # {is_instance:human, country_of_origin:Germany, profession:linguist}
    select=[("P21", "Gender"), ("P19", "City of Birth")],
    limit=15,
    default_language="en"
).to_pandas()

results

                                   item Gender        City_of_Birth
0                        Hermann Weller   male     Schwäbisch Gmünd
1                             Hans Wehr   male              Leipzig
2                       Theodor Haecker   male            Mulfingen
3                   Gottfried Bernhardy   male  Gorzów Wielkopolski
4                    Wilhelm Streitberg   male   Rüdesheim am Rhein
5                 Adalbert Bezzenberger   male               Kassel
6                     Otto Gildemeister   male               Bremen
7                     Martin Haspelmath   male                 Hoya
8                          Werner Spies   male             Tübingen
9                        Wilhelm Schott   male                Mainz
10                        Theodor Bergk   male              Leipzig
11                   Johann Ernst Glück   male               Wettin
12  August Johann Gottfried Bielenstein   male              Jelgava
13            Rudolf Alexander Schröder   male               Bremen
14                       Gerhard Rohlfs   male               Berlin

In [2]:
from wikidataloader import WikidataQuery

# Images and temperatures of stars

results = WikidataQuery.search(
    filters={"P31": "Q523"}, # {is_instance:star}
    select=[("P6879", "Temperature"), ("P18", "image_url")],
    required_properties={"P18", "P6879"},
    limit=15,
    default_language="[AUTO_LANGUAGE]"
).to_pandas()

results

,item,Temperature,image_url
0,HD 164922,5393,http://commons.wikimedia.org/wiki/Special:File...
1,Beta Phoenicis,5090,http://commons.wikimedia.org/wiki/Special:File...
2,Kepler-78,5073,http://commons.wikimedia.org/wiki/Special:File...
3,NGC 4349-127,4512,http://commons.wikimedia.org/wiki/Special:File...
4,Paradys,4090,http://commons.wikimedia.org/wiki/Special:File...
5,RS Puppis,5068,http://commons.wikimedia.org/wiki/Special:File...
6,RS Puppis,5073,http://commons.wikimedia.org/wiki/Special:File...
7,Alpha Sagittae,5503,http://commons.wikimedia.org/wiki/Special:File...
8,KY Cygni,3500,http://commons.wikimedia.org/wiki/Special:File...
9,Pi Aurigae,3736,http://commons.wikimedia.org/wiki/Special:File...
10,HD 69830,5402,http://commons.wikimedia.org/wiki/Special:File...
11,Beta Aquarii,5465,http://commons.wikimedia.org/wiki/Special:File...
12,L 34-26,3406,http://commons.wikimedia.org/wiki/Special:File...
13,BD+20 2457,4259,http://commons.wikimedia.org/wiki/Special:File...
14,TZ Arietis,3154,http://commons.wikimedia.org/wiki/Special:File...

In [3]:
from wikidataloader import WikidataQuery

# Audio pronounciations of given names

results = WikidataQuery.search(
    filters={"P31": "Q202444"}, # {is_instance:given_name}
    select=[("P407", "Language of origin"), ("P443", "audio_url")],
    required_properties={"P443"},
    limit=15,
    default_language="en"
).to_pandas()

results

,item,Language_of_origin,audio_url
0,Indy,Dutch,http://commons.wikimedia.org/wiki/Special:File...
1,Lari,Finnish,http://commons.wikimedia.org/wiki/Special:File...
2,Marthe,French,http://commons.wikimedia.org/wiki/Special:File...
3,Nathalie,Dutch,http://commons.wikimedia.org/wiki/Special:File...
4,Nathalie,Dutch,http://commons.wikimedia.org/wiki/Special:File...
5,Marcos,Spanish,http://commons.wikimedia.org/wiki/Special:File...
6,Sam,English,http://commons.wikimedia.org/wiki/Special:File...
7,Sam,English,http://commons.wikimedia.org/wiki/Special:File...
8,Uno,Estonian,http://commons.wikimedia.org/wiki/Special:File...
9,Uno,Finnish,http://commons.wikimedia.org/wiki/Special:File...
10,Aura,Finnish,http://commons.wikimedia.org/wiki/Special:File...
11,Nathalie,North Germanic,http://commons.wikimedia.org/wiki/Special:File...
12,Nathalie,North Germanic,http://commons.wikimedia.org/wiki/Special:File...
13,Kehinde,Yoruba,http://commons.wikimedia.org/wiki/Special:File...
14,Toni,multiple languages,http://commons.wikimedia.org/wiki/Special:File...

In [4]:
from wikidataloader import WikidataQuery

# Capital cities and languages of African countries with coordinates

results = WikidataQuery.search(
    filters={"P31": "Q3624078", "P30": "Q15"}, # {is_instance:country, continent:Africa}
    negative_filters={"P31": "Q3024240", "P31": "Q28171280"}, # not: {is_instance: historical_country, is_instance:ancient_civilization}
    select=[("P36", "Capital"), ("P37", "Language"), ("P625", "Coordinates")],
    limit=15,
    default_language="en"
).to_pandas()

results

,item,Capital,Language,Coordinates
0,Chad,N'Djamena,French,Point(19.4 15.466667)
1,Chad,N'Djamena,Arabic,Point(19.4 15.466667)
2,Eswatini,Mbabane,Swazi,Point(31.433333 -26.483333)
3,Somalia,Mogadishu,Somali,Point(47.0 6.0)
4,South Africa,Cape Town,South African Sign Language,Point(24.0 -29.0)
5,South Africa,Pretoria,South African Sign Language,Point(24.0 -29.0)
6,Sierra Leone,Freetown,English,Point(-12.1 8.5)
7,Seychelles,Victoria,Seychellois Creole,Point(52.766667 -7.1)
8,South Africa,Cape Town,Northern Sotho,Point(24.0 -29.0)
9,South Africa,Pretoria,Northern Sotho,Point(24.0 -29.0)
10,South Africa,Cape Town,Sesotho,Point(24.0 -29.0)
11,South Africa,Cape Town,Tsonga,Point(24.0 -29.0)
12,South Africa,Pretoria,Sesotho,Point(24.0 -29.0)
13,South Africa,Pretoria,Tsonga,Point(24.0 -29.0)
14,Somalia,Mogadishu,Arabic,Point(47.0 6.0)

In [5]:
from wikidataloader import WikidataQuery

# Color terms with lexicographical information

results = WikidataQuery.search(
    filters={"P31": "Q376431"}, # {is_instance:color_term}
    retrieve_lexicographical_information=True,
    limit=11,
    default_language="en"
).to_pandas()

results

        item    lemma        language lexical_category
0   L1196745  stålgrå          Danish        adjective
1   L1012625    slaty         English        adjective
2     L39529      grå         Swedish        adjective
3   L1012643   स्लेटी      Hindustani        adjective
4   L1012643    سلیٹی      Hindustani        adjective
5     L21315  *raudaz  Proto-Germanic        adjective
6   L1198980    عنابی     New Persian        adjective
7   L1198980   уннобӣ     New Persian        adjective
8   L1012624    سلیٹی          Hindko        adjective
9   L1126324     rode           Dutch             noun
10  L1368389      لال     New Persian        adjective