In [1]:
from wikidataloader import WikidataQuery

# Cooks from Germany with birth places

results = WikidataQuery.search(
    filters={"P31": "Q5", "P27": "Q183", "P106": "Q156839"}, # {is_instance:human, country_of_origin:Germany, profession:cook}
    select=[("P21", "Gender"), ("P19", "City of Birth")],
    limit=15,
    default_language="en"
).to_pandas()

results

                       item  Gender     City_of_Birth
0        Christian Scharrer    male  Waldshut-Tiengen
1         Christian Grainer    male         Kirchdorf
2          Michael Hoffmann    male        Dillenburg
3             Björn Freitag    male     Gelsenkirchen
4       Peter Maria Schnurr    male           Forbach
5              Franz Keller    male        Oberbergen
6           Fritz Schilling    male         Nürtingen
7        Christian Grünwald    male  Wangen im Allgäu
8        Hans-Joachim Fuchs    male              None
9              Frank Oehler    male      Mussenhausen
10            Dieter Müller    male            Auggen
11          Christian Henze    male            Füssen
12    Jacqueline Amirfallah  female         Göttingen
13        Christian Jürgens    male              Unna
14  Doris-Katharina Hessler  female              None

In [2]:
# Images of stars

results = WikidataQuery.search(
    filters={"P31": "Q523"}, # {is_instance:star}
    select=[("P6879", "Temperature"), ("P18", "image_url")],
    limit=50,
    default_language="[AUTO_LANGUAGE]"
).to_pandas().dropna()

results

,item,Temperature,image_url
2,KY Cygni,3500,http://commons.wikimedia.org/wiki/Special:File...
6,Gamma Lupi,22210,http://commons.wikimedia.org/wiki/Special:File...
8,WASP-12,6269.3335,http://commons.wikimedia.org/wiki/Special:File...
9,2MASS J00361617+1821104,1900,http://commons.wikimedia.org/wiki/Special:File...
11,2MASS J15074769-1627386,1900,http://commons.wikimedia.org/wiki/Special:File...
12,HD 209458,6118,http://commons.wikimedia.org/wiki/Special:File...

In [5]:
# Capital cities and languages of African countries with coordinates

results = WikidataQuery.search(
    filters={"P31": "Q3624078", "P30": "Q15"}, # {is_instance:country, continent:Africa}
    negative_filters={"P31": "Q3024240", "P31": "Q28171280"}, # not: {is_instance: historical_country, is_instance:ancient_civilization}
    select=[("P36", "Capital"), ("P37", "Language"), ("P625", "Coordinates")],
    limit=15,
    default_language="en"
).to_pandas()

results

,item,Capital,Language,Coordinates
0,Burundi,Gitega,English,Point(29.816667 -3.666667)
1,The Gambia,Banjul,English,Point(-15.5 13.5)
2,Mali,Bamako,Fula,Point(-4.0 17.0)
3,Democratic Republic of the Congo,Kinshasa,French,Point(23.656111111 -2.88)
4,Zimbabwe,Harare,Zimbabwe Sign Language,Point(30.0 -19.0)
5,Libya,Tripoli,Arabic,Point(17.0 27.0)
6,Cape Verde,Praia,Portuguese,Point(-23.7 15.3)
7,Angola,Luanda,Portuguese,Point(17.35 -12.35)
8,Malawi,Lilongwe,Tumbuka,Point(34.0 -13.0)
9,São Tomé and Príncipe,São Tomé,Portuguese,Point(6.6 0.316667)
10,Lesotho,Maseru,English,Point(28.25 -29.55)
11,Madagascar,Antananarivo,French,Point(47.0 -20.0)
12,Madagascar,Antananarivo,Malagasy,Point(47.0 -20.0)
13,Burundi,Gitega,French,Point(29.816667 -3.666667)
14,Comoros,Moroni,French,Point(43.7 -12.3)

In [4]:
# List of phrases

results = WikidataQuery.search(
    filters={"P31": "Q187931"}, # {is_instance:phrase}
    limit=15,
    default_language="en"
).to_pandas()

list(results["item"])

['To be, or not to be',
 'genius loci',
 'Item',
 'a picture is worth a thousand words',
 'Mulus',
 'Minus',
 'Cash is king',
 'That that is is that that is not is not is that it it is.',
 'Studia humanitatis',
 'Chorismos',
 'Concursus Dei',
 'Condictio causa data non secuta',
 'Condictio certae pecuniae',
 'Condictio certae rei',
 'Condictio ob causam finitam']